/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.CPagarDAO;
import dao.CReceberDAO;
import entity.CPagar;
import entity.CReceber;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gabriel1
 */
public class TelaCaixa extends javax.swing.JDialog {

    /**
     * Creates new form Caixa
     */
    public TelaCaixa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        try {
            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
            String data = formatter.format(new Date());
            txtData.setText(data);
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            d = sdf.parse(txtData.getText());
        } catch (ParseException ex) {
            Logger.getLogger(TelaCaixa.class.getName()).log(Level.SEVERE, null, ex);
        }
        dt = new java.sql.Date(d.getTime());
        tabelaEntradas(dt);
        somaEntradas();
        txtDataFim.setVisible(false);
        btnAtualizar.setVisible(false);
        tabelaSaidas();
        somaSaidas();
        caixa();
    }

    DecimalFormat df = new DecimalFormat("####.00");
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    Date d;
    java.sql.Date dt;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSaida = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblEntrada = new javax.swing.JLabel();
        lblSaida = new javax.swing.JLabel();
        lblCaixa = new javax.swing.JLabel();
        txtData = new javax.swing.JFormattedTextField();
        lblData = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtDataFim = new javax.swing.JFormattedTextField();
        btnAtualizar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnEntrada = new javax.swing.JButton();
        rbtnEntradaPrazo = new javax.swing.JRadioButton();
        rbtnEntradaAVista = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnSaida = new javax.swing.JButton();
        rbtnSaidaAVista = new javax.swing.JRadioButton();
        rbtnSaidaPrazo = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblEntrada = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Caixa - Agenda Financeira");

        tblSaida.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 51, 153)));
        tblSaida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Documento", "Descrição", "Data", "Valor", "Vencimento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSaida.setShowHorizontalLines(true);
        tblSaida.setShowVerticalLines(true);
        jScrollPane1.setViewportView(tblSaida);
        if (tblSaida.getColumnModel().getColumnCount() > 0) {
            tblSaida.getColumnModel().getColumn(0).setPreferredWidth(150);
            tblSaida.getColumnModel().getColumn(1).setResizable(false);
            tblSaida.getColumnModel().getColumn(1).setPreferredWidth(20);
            tblSaida.getColumnModel().getColumn(2).setPreferredWidth(220);
            tblSaida.getColumnModel().getColumn(3).setPreferredWidth(20);
            tblSaida.getColumnModel().getColumn(4).setPreferredWidth(40);
            tblSaida.getColumnModel().getColumn(5).setPreferredWidth(20);
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 51, 153)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Entradas R$");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 549, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Saídas R$");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 578, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Caixa R$");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 607, -1, -1));

        lblEntrada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEntrada.setText("0,00");
        jPanel1.add(lblEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 549, -1, -1));

        lblSaida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSaida.setText("0,00");
        jPanel1.add(lblSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 578, -1, -1));

        lblCaixa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCaixa.setText("0,00");
        jPanel1.add(lblCaixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 607, -1, -1));

        txtData.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtData.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDataKeyPressed(evt);
            }
        });
        jPanel1.add(txtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 108, -1));

        lblData.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblData.setText("Data:");
        lblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDataMouseClicked(evt);
            }
        });
        jPanel1.add(lblData, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel6.setText("Nome");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 125, -1, -1));

        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 141, 260, 25));

        jLabel7.setText("Fatura");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 172, -1, -1));

        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 188, 98, 25));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Find.png"))); // NOI18N
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 188, -1, -1));

        txtDataFim.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        try {
            txtDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataFim.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDataFim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDataFimKeyPressed(evt);
            }
        });
        jPanel1.add(txtDataFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 108, -1));

        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Refresh.png"))); // NOI18N
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 40, -1));

        jPanel2.setBackground(new java.awt.Color(0, 51, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ENTRADAS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        btnEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Raise.png"))); // NOI18N
        btnEntrada.setText("Entrada");
        btnEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradaActionPerformed(evt);
            }
        });
        jPanel2.add(btnEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(724, 13, -1, -1));

        buttonGroup1.add(rbtnEntradaPrazo);
        rbtnEntradaPrazo.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        rbtnEntradaPrazo.setForeground(new java.awt.Color(255, 255, 255));
        rbtnEntradaPrazo.setText("Prazo");
        rbtnEntradaPrazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnEntradaPrazoActionPerformed(evt);
            }
        });
        jPanel2.add(rbtnEntradaPrazo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        buttonGroup1.add(rbtnEntradaAVista);
        rbtnEntradaAVista.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        rbtnEntradaAVista.setForeground(new java.awt.Color(255, 255, 255));
        rbtnEntradaAVista.setSelected(true);
        rbtnEntradaAVista.setText("A Vista");
        rbtnEntradaAVista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnEntradaAVistaActionPerformed(evt);
            }
        });
        jPanel2.add(rbtnEntradaAVista, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 51, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SAÍDAS");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 16, -1, -1));

        btnSaida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Fall.png"))); // NOI18N
        btnSaida.setText("Saída");
        btnSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaidaActionPerformed(evt);
            }
        });
        jPanel3.add(btnSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 91, -1));

        buttonGroup2.add(rbtnSaidaAVista);
        rbtnSaidaAVista.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        rbtnSaidaAVista.setForeground(new java.awt.Color(255, 255, 255));
        rbtnSaidaAVista.setSelected(true);
        rbtnSaidaAVista.setText("A Vista");
        jPanel3.add(rbtnSaidaAVista, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, -1));

        buttonGroup2.add(rbtnSaidaPrazo);
        rbtnSaidaPrazo.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        rbtnSaidaPrazo.setForeground(new java.awt.Color(255, 255, 255));
        rbtnSaidaPrazo.setText("Prazo");
        jPanel3.add(rbtnSaidaPrazo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        tblEntrada.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 51, 153)));
        tblEntrada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Documento", "Descrição", "Data", "Valor", "Vencimento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEntrada.setShowHorizontalLines(true);
        tblEntrada.setShowVerticalLines(true);
        jScrollPane3.setViewportView(tblEntrada);
        if (tblEntrada.getColumnModel().getColumnCount() > 0) {
            tblEntrada.getColumnModel().getColumn(0).setPreferredWidth(150);
            tblEntrada.getColumnModel().getColumn(1).setResizable(false);
            tblEntrada.getColumnModel().getColumn(1).setPreferredWidth(20);
            tblEntrada.getColumnModel().getColumn(2).setPreferredWidth(220);
            tblEntrada.getColumnModel().getColumn(3).setPreferredWidth(20);
            tblEntrada.getColumnModel().getColumn(4).setPreferredWidth(50);
            tblEntrada.getColumnModel().getColumn(5).setPreferredWidth(20);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 817, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradaActionPerformed
        TelaContasAReceber tela = new TelaContasAReceber(null, rootPaneCheckingEnabled, null);
        tela.setVisible(true);
    }//GEN-LAST:event_btnEntradaActionPerformed

    private void btnSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaidaActionPerformed
        TelaContasAPagar tela = new TelaContasAPagar(null, rootPaneCheckingEnabled);
        tela.setVisible(true);
    }//GEN-LAST:event_btnSaidaActionPerformed

    private void txtDataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDataKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            try {
                d = sdf.parse(txtData.getText());
            } catch (ParseException ex) {
                Logger.getLogger(TelaCaixa.class.getName()).log(Level.SEVERE, null, ex);
            }
            dt = new java.sql.Date(d.getTime());
            if (rbtnEntradaAVista.isSelected()) {
                tabelaEntradas(dt);
                somaEntradas();
            } else if (rbtnEntradaPrazo.isSelected()) {
                tabelaEntradasPrazo(d);
                somaEntradas();
            }
        }
    }//GEN-LAST:event_txtDataKeyPressed

    private void rbtnEntradaAVistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnEntradaAVistaActionPerformed
        try {
            d = sdf.parse(txtData.getText());
        } catch (ParseException ex) {
            Logger.getLogger(TelaCaixa.class.getName()).log(Level.SEVERE, null, ex);
        }
        dt = new java.sql.Date(d.getTime());
        tabelaEntradas(dt);
        somaEntradas();
        caixa();
    }//GEN-LAST:event_rbtnEntradaAVistaActionPerformed

    private void rbtnEntradaPrazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnEntradaPrazoActionPerformed
        try {
            d = sdf.parse(txtData.getText());
        } catch (ParseException ex) {
            Logger.getLogger(TelaCaixa.class.getName()).log(Level.SEVERE, null, ex);
        }
        dt = new java.sql.Date(d.getTime());
        tabelaEntradasPrazo(dt);
        somaEntradas();
        caixa();
    }//GEN-LAST:event_rbtnEntradaPrazoActionPerformed

    private void lblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDataMouseClicked
        if (lblData.getText().equals("Data:")) {
            lblData.setText("Período:");
            txtDataFim.setVisible(true);
            btnAtualizar.setVisible(true);
        } else if (lblData.getText().equals("Período:")) {
            lblData.setText("Data:");
            txtDataFim.setVisible(false);
            btnAtualizar.setVisible(false);
        }
    }//GEN-LAST:event_lblDataMouseClicked

    private void txtDataFimKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDataFimKeyPressed
       
    }//GEN-LAST:event_txtDataFimKeyPressed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
         Date data = new Date();
        txtData.setText(sdf.format(data));
        tabelaSaidas();
        tabelaEntradas(data);
        somaEntradas();
        somaSaidas();
        caixa();
        txtDataFim.setVisible(false);
        btnAtualizar.setVisible(false);
    }//GEN-LAST:event_btnAtualizarActionPerformed

    public void tabelaEntradas(Date data) {
        DefaultTableModel model = (DefaultTableModel) tblEntrada.getModel();
        CReceberDAO crDAO = new CReceberDAO();
        List<CReceber> lista = crDAO.listarCReceberAVista((java.sql.Date) data);
        model.setNumRows(0);
        for (int i = 0; i < lista.size(); i++) {
            model.addRow(new Object[]{});
            model.setValueAt(lista.get(i).getP().getNome(), i, 0);
            model.setValueAt(lista.get(i).getFatura(), i, 1);
            model.setValueAt(lista.get(i).getFormPagamento(), i, 2);
            model.setValueAt(sdf.format(lista.get(i).getData()), i, 3);
            model.setValueAt(df.format(lista.get(i).getTotal()), i, 4);
            model.setValueAt(sdf.format(lista.get(i).getVencimento()), i, 5);
        }
    }

    public void tabelaEntradasPrazo(Date data) {
        DefaultTableModel model = (DefaultTableModel) tblEntrada.getModel();
        CReceberDAO crDAO = new CReceberDAO();
        List<CReceber> lista = crDAO.listarCReceberPrazo((java.sql.Date) data);
        model.setNumRows(0);
        for (int i = 0; i < lista.size(); i++) {
            model.addRow(new Object[]{});
            model.setValueAt(lista.get(i).getP().getNome(), i, 0);
            model.setValueAt(lista.get(i).getFatura(), i, 1);
            model.setValueAt(lista.get(i).getFormPagamento(), i, 2);
            model.setValueAt(sdf.format(lista.get(i).getData()), i, 3);
            model.setValueAt(df.format(lista.get(i).getTotal()), i, 4);
            model.setValueAt(sdf.format(lista.get(i).getVencimento()), i, 5);
        }
    }

    public void tabelaSaidas() {
        DefaultTableModel model = (DefaultTableModel) tblSaida.getModel();
        CPagarDAO cpDAO = new CPagarDAO();
        List<CPagar> lista = cpDAO.listarCPagarAVista(dt);
        model.setNumRows(0);
        for (int i = 0; i < lista.size(); i++) {
            model.addRow(new Object[]{});
            model.setValueAt(lista.get(i).getP().getNome(), i, 0);
            model.setValueAt(lista.get(i).getFatura(), i, 1);
            model.setValueAt(lista.get(i).getFormPagamento(), i, 2);
            model.setValueAt(lista.get(i).getData(), i, 3);
            model.setValueAt(df.format(lista.get(i).getTotal()), i, 4);
            model.setValueAt(lista.get(i).getVencimento(), i, 5);
        }
    }

    public void somaEntradas() {
        DefaultTableModel model = (DefaultTableModel) tblEntrada.getModel();
        double valor = 0;
        double resultado = 0;
        for (int i = 0; i < tblEntrada.getRowCount(); i++) {
            valor = Double.parseDouble(tblEntrada.getValueAt(i, 4).toString().replace(",", "."));
            resultado += valor;
        }
        lblEntrada.setText(df.format(resultado) + "");
    }

    public void somaSaidas() {
        DefaultTableModel model = (DefaultTableModel) tblSaida.getModel();
        double valor = 0;
        double resultado = 0;
        for (int i = 0; i < tblSaida.getRowCount(); i++) {
            valor = Double.parseDouble(tblSaida.getValueAt(i, 4).toString().replace(",", "."));
            resultado += valor;
        }
        lblSaida.setText(df.format(resultado) + "");
    }

    public void caixa() {
        Double entrada = Double.parseDouble(lblEntrada.getText().replace(",", "."));
        Double saida = Double.parseDouble(lblSaida.getText().replace(",", "."));
        Double resultado = entrada - saida;
        lblCaixa.setText(df.format(resultado));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCaixa.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCaixa.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCaixa.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCaixa.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaCaixa dialog = new TelaCaixa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnEntrada;
    private javax.swing.JButton btnSaida;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblCaixa;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblEntrada;
    private javax.swing.JLabel lblSaida;
    private javax.swing.JRadioButton rbtnEntradaAVista;
    private javax.swing.JRadioButton rbtnEntradaPrazo;
    private javax.swing.JRadioButton rbtnSaidaAVista;
    private javax.swing.JRadioButton rbtnSaidaPrazo;
    private javax.swing.JTable tblEntrada;
    private javax.swing.JTable tblSaida;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JFormattedTextField txtDataFim;
    // End of variables declaration//GEN-END:variables
}
