/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.OrcamentoDAO;
import dao.ProdutoDAO;
import dao.ProdutoOrcamentoDAO;
import entity.Orcamento;
import entity.Pessoa;
import entity.Produto;
import entity.ProdutoOrcamento;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gabriel1
 */
public class TelaOrcamento extends javax.swing.JDialog {

    /**
     * Creates new form Orcamento
     */
    public TelaOrcamento(java.awt.Frame parent, boolean modal, Pessoa p) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        lblAprovado.setVisible(false);
        try {
            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
            String data = formatter.format(new Date());
            txtData.setText(data);
        } catch (Exception e) {
            e.printStackTrace();
        }
        if (p != null) {
            this.ps = p;
            txtCodPessoa.setText(ps.getIdPessoa() + "");
            txtNome.setText(ps.getNome());
        } else {

        }
    }

    Pessoa ps = new Pessoa();
    ProdutoDAO pDAO = new ProdutoDAO();
    OrcamentoDAO oDAO = new OrcamentoDAO();
    ProdutoOrcamentoDAO pdDAO = new ProdutoOrcamentoDAO();
    Produto p = new Produto();
    Orcamento o = new Orcamento();
    List<ProdutoOrcamento> lista;
    int contador = 0;
    double resultado;
    double totalOrçamento;
    double totalDesconto;
    SimpleDateFormat sdfD = new SimpleDateFormat("dd/MM/yyyy");
    SimpleDateFormat sdfH = new SimpleDateFormat("HH:mm");
    DecimalFormat df = new DecimalFormat("####.00");
    DefaultTableCellRenderer esquerda = new DefaultTableCellRenderer();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtOrcamento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtData = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCodProduto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtQtdProduto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduto = new javax.swing.JTable();
        btnAprovado = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        lblTotalOrcamento = new javax.swing.JLabel();
        btnLimpaDesconto = new javax.swing.JButton();
        btnRemoveProduto = new javax.swing.JButton();
        lblDescontoItem = new javax.swing.JLabel();
        txtDescontoProduto = new javax.swing.JTextField();
        lblDescontoOrcamento = new javax.swing.JLabel();
        txtDescontoOrcamento = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnPesquisaCliente = new javax.swing.JButton();
        txtPesquisaOrcamento = new javax.swing.JButton();
        btnPesquisaProduto = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtCodPessoa = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lblTotalItem = new javax.swing.JLabel();
        btnAddProduto = new javax.swing.JButton();
        btnLimparTela = new javax.swing.JButton();
        btnLimpaDescontoOrcamento = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnLimpaProduto = new javax.swing.JButton();
        lblAprovado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Orçamento - Agenda Financeira");

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 51, 153)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nome:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 66, -1, -1));

        txtNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeKeyReleased(evt);
            }
        });
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 82, 480, -1));

        jLabel2.setText("Orçamento");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 10, -1, -1));

        txtOrcamento.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtOrcamento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        txtOrcamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOrcamentoKeyReleased(evt);
            }
        });
        jPanel1.add(txtOrcamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 30, 80, -1));

        jLabel3.setText("Data");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        txtData.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 80, -1));

        jLabel4.setText("Produto");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 115, -1, -1));

        txtProduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        txtProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProdutoKeyReleased(evt);
            }
        });
        jPanel1.add(txtProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 131, 480, -1));

        jLabel5.setText("Cd. Produto");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 115, -1, -1));

        txtCodProduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        jPanel1.add(txtCodProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 131, 80, -1));

        jLabel6.setText("Qtd");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 160, -1, -1));

        txtQtdProduto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtQtdProduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        txtQtdProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQtdProdutoKeyReleased(evt);
            }
        });
        jPanel1.add(txtQtdProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 176, 50, -1));

        jLabel7.setText("Valor R$");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        txtValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorKeyReleased(evt);
            }
        });
        jPanel1.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 176, 82, -1));

        tblProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cd Produto", "Produto", "Qtd", "R$ Unit.", "R$ Total"
            }
        ));
        jScrollPane1.setViewportView(tblProduto);
        if (tblProduto.getColumnModel().getColumnCount() > 0) {
            tblProduto.getColumnModel().getColumn(0).setResizable(false);
            tblProduto.getColumnModel().getColumn(0).setPreferredWidth(40);
            tblProduto.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblProduto.getColumnModel().getColumn(2).setResizable(false);
            tblProduto.getColumnModel().getColumn(2).setPreferredWidth(20);
            tblProduto.getColumnModel().getColumn(3).setResizable(false);
            tblProduto.getColumnModel().getColumn(3).setPreferredWidth(50);
            tblProduto.getColumnModel().getColumn(4).setPreferredWidth(60);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 208, 616, 326));

        btnAprovado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Good mark.png"))); // NOI18N
        btnAprovado.setText("Aprovado");
        btnAprovado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAprovadoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAprovado, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 581, -1, -1));

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Modify.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        jPanel1.add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 581, -1, -1));

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 581, -1, -1));

        jLabel17.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 0, 0));
        jLabel17.setText("Total Orçamento R$");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 550, -1, -1));

        lblTotalOrcamento.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblTotalOrcamento.setForeground(new java.awt.Color(204, 0, 0));
        lblTotalOrcamento.setText("0,00");
        jPanel1.add(lblTotalOrcamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 550, -1, -1));

        btnLimpaDesconto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Refresh.png"))); // NOI18N
        btnLimpaDesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpaDescontoActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpaDesconto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        btnRemoveProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/No-entry.png"))); // NOI18N
        btnRemoveProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(btnRemoveProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 174, -1, -1));

        lblDescontoItem.setForeground(new java.awt.Color(204, 0, 0));
        lblDescontoItem.setText("*Desconto %");
        lblDescontoItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblDescontoItemMousePressed(evt);
            }
        });
        jPanel1.add(lblDescontoItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        txtDescontoProduto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDescontoProduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        txtDescontoProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescontoProdutoKeyReleased(evt);
            }
        });
        jPanel1.add(txtDescontoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 176, 80, -1));

        lblDescontoOrcamento.setForeground(new java.awt.Color(204, 0, 0));
        lblDescontoOrcamento.setText("*Desconto %");
        lblDescontoOrcamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblDescontoOrcamentoMousePressed(evt);
            }
        });
        jPanel1.add(lblDescontoOrcamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, -1, 20));

        txtDescontoOrcamento.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDescontoOrcamento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        txtDescontoOrcamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescontoOrcamentoKeyReleased(evt);
            }
        });
        jPanel1.add(txtDescontoOrcamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 550, 77, -1));

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Apply.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 581, -1, -1));

        btnPesquisaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Find.png"))); // NOI18N
        btnPesquisaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnPesquisaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, -1, 37));

        txtPesquisaOrcamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Find.png"))); // NOI18N
        txtPesquisaOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaOrcamentoActionPerformed(evt);
            }
        });
        jPanel1.add(txtPesquisaOrcamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 16, -1, 37));

        btnPesquisaProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Find.png"))); // NOI18N
        btnPesquisaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(btnPesquisaProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 119, -1, 37));

        jLabel8.setText("Código");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 66, -1, -1));

        txtCodPessoa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        jPanel1.add(txtCodPessoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 82, 80, -1));

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel9.setText("Total Item R$");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        lblTotalItem.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblTotalItem.setText("0,00");
        jPanel1.add(lblTotalItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));

        btnAddProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Create.png"))); // NOI18N
        btnAddProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 174, -1, -1));

        btnLimparTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pincel.png"))); // NOI18N
        btnLimparTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparTelaActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimparTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, -1, 30));

        btnLimpaDescontoOrcamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Refresh.png"))); // NOI18N
        btnLimpaDescontoOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpaDescontoOrcamentoActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpaDescontoOrcamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, -1, 30));

        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("* Clique para alternar entre % e R$");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

        btnLimpaProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pincel.png"))); // NOI18N
        btnLimpaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpaProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpaProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 174, -1, -1));

        lblAprovado.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        lblAprovado.setForeground(new java.awt.Color(51, 153, 0));
        lblAprovado.setText("ORÇAMENTO APROVADO");
        jPanel1.add(lblAprovado, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaProdutoActionPerformed
        String nome = txtProduto.getText();
        if (nome.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Digite uma letra para pesquisa");
            txtCodPessoa.setText("");
        } else {
            TelaPesquisaProduto tela = new TelaPesquisaProduto(null, rootPaneCheckingEnabled, nome);
            tela.setVisible(true);
            txtCodProduto.setText(tela.p.getIdProduto() + "");
            txtProduto.setText(tela.p.getDescricao());
            txtValor.setText(df.format(tela.p.getValorVenda()) + "");
        }
    }//GEN-LAST:event_btnPesquisaProdutoActionPerformed

    private void btnPesquisaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaClienteActionPerformed
        String nome = txtNome.getText();
        if (nome.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Digite uma letra para pesquisa");
        } else {
            TelaPesquisaPessoa tela = new TelaPesquisaPessoa(null, rootPaneCheckingEnabled, nome);
            tela.setVisible(true);
            txtCodPessoa.setText(tela.p.getIdPessoa() + "");
            txtNome.setText(tela.p.getNome());
        }
    }//GEN-LAST:event_btnPesquisaClienteActionPerformed

    private void btnLimpaDescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpaDescontoActionPerformed
        try {
            txtDescontoProduto.setEnabled(true);
            txtDescontoProduto.setText("");
            String quantidade = txtQtdProduto.getText().replaceAll(",", ".");
            String vl = txtValor.getText().replaceAll(",", ".");
            double qtd = Double.parseDouble(quantidade);
            double valor = Double.parseDouble(vl);
            resultado = qtd * valor;
            lblTotalItem.setText(df.format(resultado) + "");
        } catch (NumberFormatException e) {
        }
    }//GEN-LAST:event_btnLimpaDescontoActionPerformed

    private void btnRemoveProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveProdutoActionPerformed
        DefaultTableModel tbl = (DefaultTableModel) this.tblProduto.getModel();
        int linha = tblProduto.getSelectedRow();
        if (tblProduto.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um produto para excluir");
        } else {
            String vl = tbl.getValueAt(linha, 4).toString().replaceAll(",", ".");
            Double valor = Double.parseDouble(vl);
            totalOrçamento -= valor;
            tbl.removeRow(linha);
            lblTotalOrcamento.setText(df.format(totalOrçamento) + "");
            if (lblTotalOrcamento.getText().equals(",00")) {
                lblTotalOrcamento.setText("0,00");
            }
        }
    }//GEN-LAST:event_btnRemoveProdutoActionPerformed

    private void txtQtdProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtdProdutoKeyReleased
        try {
            String quantidade = txtQtdProduto.getText().replaceAll(",", ".");
            String vl = txtValor.getText().replaceAll(",", ".");
            double qtd = Double.parseDouble(quantidade);
            double valor = Double.parseDouble(vl);
            resultado = qtd * valor;
            lblTotalItem.setText(df.format(resultado) + "");
        } catch (NumberFormatException e) {
        }
    }//GEN-LAST:event_txtQtdProdutoKeyReleased

    private void txtValorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyReleased
        try {
            String quantidade = txtQtdProduto.getText().replaceAll(",", ".");
            String vl = txtValor.getText().replaceAll(",", ".");
            double qtd = Double.parseDouble(quantidade);
            double valor = Double.parseDouble(vl);
            resultado = qtd * valor;
            lblTotalItem.setText(df.format(resultado) + "");
        } catch (NumberFormatException e) {
        }
    }//GEN-LAST:event_txtValorKeyReleased

    private void txtDescontoProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescontoProdutoKeyReleased
        if (evt.getKeyCode() == evt.VK_ENTER) {
            try {
                String desc = txtDescontoProduto.getText().replaceAll(",", ".");
                String vl = lblTotalItem.getText().replaceAll(",", ".");
                String teste = lblDescontoItem.getText();
                double desconto = Double.parseDouble(desc);
                double valor = Double.parseDouble(vl);
                if (teste.equals("*Desconto %")) {
                    resultado -= (desconto / 100) * valor;
                } else if (teste.equals("*Desconto R$")) {
                    resultado -= desconto;
                }
                lblTotalItem.setText(df.format(resultado) + "");
                txtDescontoProduto.setEnabled(false);
            } catch (NumberFormatException e) {
            }
        }
    }//GEN-LAST:event_txtDescontoProdutoKeyReleased

    private void btnAddProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProdutoActionPerformed
        String testeQuantidade = txtQtdProduto.getText();
        String testeProduto = txtProduto.getText();
        if (testeProduto.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Insira um Produto");
        } else {
            if (testeQuantidade.equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Insira a Quantidade");
            } else {
                contador++;
                int id = Integer.parseInt(txtCodProduto.getText());
                atualizaTabela(id);
                limpaProduto();
                totalOrçamento += resultado;
                lblTotalOrcamento.setText(totalOrçamento + "");
                txtDescontoOrcamento.setEnabled(true);
                txtDescontoOrcamento.setText("");
                lblTotalOrcamento.setText(df.format(totalOrçamento) + "");
            }
        }
    }//GEN-LAST:event_btnAddProdutoActionPerformed

    private void btnLimparTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparTelaActionPerformed
        limparTela();
    }//GEN-LAST:event_btnLimparTelaActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        String cdCliente = txtCodPessoa.getText();
        String nome = txtNome.getText();

        if (cdCliente.equals("") || nome.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Insira um Cliente");
        } else {
            if (tblProduto.getRowCount() == 0) {
                JOptionPane.showMessageDialog(rootPane, "Insira os Produtos");
            } else {
                Orcamento orcamento = new Orcamento();
                OrcamentoDAO oDAO = new OrcamentoDAO();
                ProdutoOrcamento po = new ProdutoOrcamento();
                ProdutoOrcamentoDAO poDAO = new ProdutoOrcamentoDAO();
                int linhas = tblProduto.getRowCount();

                try {
                    orcamento.setData(sdfD.parse(txtData.getText()));
                } catch (ParseException ex) {
                    Logger.getLogger(TelaOrcamento.class.getName()).log(Level.SEVERE, null, ex);
                }
                orcamento.setIdPessoa(Integer.parseInt(txtCodPessoa.getText()));
                orcamento.setNome(txtNome.getText());
                String vl = lblTotalOrcamento.getText().replaceAll(",", ".");
                orcamento.setTotal(Double.parseDouble(vl));
                orcamento.setAprovado(false);
                oDAO.insert(orcamento);
                for (int i = 0; i < linhas; i++) {
                    String vlTotal = tblProduto.getValueAt(i, 4).toString().replaceAll(",", ".");
                    String vlUnit = tblProduto.getValueAt(i, 3).toString().replaceAll(",", ".");
                    String quantidade = tblProduto.getValueAt(i, 2).toString().replaceAll(",", ".");
                    po.setIdProduto(Integer.parseInt(tblProduto.getValueAt(i, 0).toString()));
                    po.setIdOrcamento(orcamento.getIdOrcamento());
                    po.setProduto(tblProduto.getValueAt(i, 1).toString());
                    po.setQuantidade(Double.parseDouble(quantidade));
                    po.setValor(Double.parseDouble(vlUnit));
                    po.setTotal(Double.parseDouble(vlTotal));
                    poDAO.insert(po);
                }
                limparTela();
                JOptionPane.showMessageDialog(rootPane, "Salvo com Sucesso!\n"
                        + "Orçamento: " + orcamento.getIdOrcamento());
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int confirmacao = JOptionPane.showConfirmDialog(this, "Excluir Orcamento N° " + txtOrcamento.getText() + "\n"
                + "Cliente: " + txtNome.getText() + "", "Exclusão", 0, 0);
        if (confirmacao == 0) {
            int id = Integer.parseInt(txtOrcamento.getText());
            pdDAO.delete(id);
            oDAO.delete(id);
            limparTela();
            JOptionPane.showMessageDialog(rootPane, "Orçamento Excluído!");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void lblDescontoItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDescontoItemMousePressed
        String texto = lblDescontoItem.getText();
        if (texto.equals("*Desconto %")) {
            lblDescontoItem.setText("*Desconto R$");
        } else if (texto.equals("*Desconto R$")) {
            lblDescontoItem.setText("*Desconto %");
        }
    }//GEN-LAST:event_lblDescontoItemMousePressed

    private void txtDescontoOrcamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescontoOrcamentoKeyReleased
        if (evt.getKeyCode() == evt.VK_ENTER) {
            try {
                String teste = lblDescontoOrcamento.getText();
                String desc = txtDescontoOrcamento.getText().replaceAll(",", ".");
                String vl = lblTotalOrcamento.getText().replaceAll(",", ".");
                double desconto = Double.parseDouble(desc);
                double valor = Double.parseDouble(vl);
                if (teste.equals("*Desconto %")) {
                    totalDesconto = totalOrçamento - (desconto / 100) * valor;
                } else if (teste.equals("*Desconto R$")) {
                    totalDesconto = totalOrçamento - desconto;
                }
                lblTotalOrcamento.setText(df.format(totalDesconto) + "");
                txtDescontoOrcamento.setEnabled(false);
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_txtDescontoOrcamentoKeyReleased

    private void lblDescontoOrcamentoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDescontoOrcamentoMousePressed
        String texto = lblDescontoOrcamento.getText();
        if (texto.equals("*Desconto %")) {
            lblDescontoOrcamento.setText("*Desconto R$");
        } else if (texto.equals("*Desconto R$")) {
            lblDescontoOrcamento.setText("*Desconto %");
        }
    }//GEN-LAST:event_lblDescontoOrcamentoMousePressed

    private void btnLimpaDescontoOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpaDescontoOrcamentoActionPerformed
        try {
            txtDescontoOrcamento.setEnabled(true);
            txtDescontoOrcamento.setText("");
            lblTotalOrcamento.setText(df.format(totalOrçamento) + "");
        } catch (NumberFormatException e) {
        }
    }//GEN-LAST:event_btnLimpaDescontoOrcamentoActionPerformed

    private void txtNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyReleased
        if (evt.getKeyCode() == evt.VK_ENTER) {
            String nome = txtNome.getText();
            if (nome.equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Digite uma letra para pesquisa");
            } else {
                TelaPesquisaPessoa tela = new TelaPesquisaPessoa(null, rootPaneCheckingEnabled, nome);
                tela.setVisible(true);
                txtCodPessoa.setText(tela.p.getIdPessoa() + "");
                txtNome.setText(tela.p.getNome());
            }
        }
    }//GEN-LAST:event_txtNomeKeyReleased

    private void txtProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProdutoKeyReleased
        if (evt.getKeyCode() == evt.VK_ENTER) {
            String nome = txtProduto.getText();
            if (nome.equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Digite uma letra para pesquisa");
                txtCodPessoa.setText("");
            } else {
                TelaPesquisaProduto tela = new TelaPesquisaProduto(null, rootPaneCheckingEnabled, nome);
                tela.setVisible(true);
                txtCodProduto.setText(tela.p.getIdProduto() + "");
                txtProduto.setText(tela.p.getDescricao());
                txtValor.setText(df.format(tela.p.getValorVenda()) + "");
            }
        }
    }//GEN-LAST:event_txtProdutoKeyReleased

    private void txtPesquisaOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaOrcamentoActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblProduto.getModel();
        esquerda.setHorizontalAlignment(SwingConstants.RIGHT);
        tblProduto.getColumnModel().getColumn(2).setCellRenderer(esquerda);
        tblProduto.getColumnModel().getColumn(3).setCellRenderer(esquerda);
        tblProduto.getColumnModel().getColumn(4).setCellRenderer(esquerda);
        TelaPesquisaOrcamento tela = new TelaPesquisaOrcamento(null, rootPaneCheckingEnabled, 0);
        tela.setVisible(true);
        boolean aprovado = tela.o.isAprovado();
        if (tela.o.getIdOrcamento() == 0 || tela.o.getIdPessoa() == 0) {
            limparTela();
        } else {
            if(aprovado){
                botao();
            }else if(!aprovado){
                botaoVisible();
            }
            txtOrcamento.setText(tela.o.getIdOrcamento() + "");
            txtCodPessoa.setText(tela.o.getIdPessoa() + "");
            txtNome.setText(tela.o.getNome());
            lblTotalOrcamento.setText(df.format(tela.o.getTotal()) + "");
            model.setNumRows(0);
            for (int i = 0; i < tela.listaPOrcamento.size(); i++) {
                model.addRow(new Object[]{});
                model.setValueAt(tela.listaPOrcamento.get(i).getIdProduto(), i, 0);
                model.setValueAt(tela.listaPOrcamento.get(i).getProduto(), i, 1);
                model.setValueAt(tela.listaPOrcamento.get(i).getQuantidade(), i, 2);
                model.setValueAt(df.format(tela.listaPOrcamento.get(i).getValor()), i, 3);
                model.setValueAt(df.format(tela.listaPOrcamento.get(i).getTotal()), i, 4);
            }
        }
    }//GEN-LAST:event_txtPesquisaOrcamentoActionPerformed

    private void txtOrcamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOrcamentoKeyReleased
        if (evt.getKeyCode() == evt.VK_ENTER) {
            try {
                int cd = Integer.parseInt(txtOrcamento.getText());
                TelaPesquisaOrcamento tela = new TelaPesquisaOrcamento(null, rootPaneCheckingEnabled, cd);
                tela.setVisible(true);
            } catch (NumberFormatException e) {
            }
        }
    }//GEN-LAST:event_txtOrcamentoKeyReleased

    private void btnLimpaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpaProdutoActionPerformed
        limpaProduto();
    }//GEN-LAST:event_btnLimpaProdutoActionPerformed

    private void btnAprovadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAprovadoActionPerformed
        int id = Integer.parseInt(txtOrcamento.getText());
        oDAO.update(id);
        botao();     
        String vl = lblTotalOrcamento.getText().replaceAll(",", ".");               
        o.setIdOrcamento(Integer.parseInt(txtOrcamento.getText()));
        o.setIdPessoa(Integer.parseInt(txtCodPessoa.getText()));
        o.setNome(txtNome.getText());
        o.setIdOrcamento(Integer.parseInt(txtOrcamento.getText()));
        try {
            o.setData(sdfD.parse(txtData.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(TelaOrcamento.class.getName()).log(Level.SEVERE, null, ex);
        }
        o.setTotal(Double.parseDouble(vl));
        TelaContasAReceber tela = new TelaContasAReceber(null, rootPaneCheckingEnabled, o);
        tela.setVisible(true);
    }//GEN-LAST:event_btnAprovadoActionPerformed

    public void atualizaTabela(int id) {
        DefaultTableModel tbl = (DefaultTableModel) this.tblProduto.getModel();
        esquerda.setHorizontalAlignment(SwingConstants.RIGHT);
        tblProduto.getColumnModel().getColumn(2).setCellRenderer(esquerda);
        tblProduto.getColumnModel().getColumn(3).setCellRenderer(esquerda);
        tblProduto.getColumnModel().getColumn(4).setCellRenderer(esquerda);
        p = pDAO.getProdutoById(id);
        tbl.addRow(new Object[]{p.getIdProduto(), p.getDescricao(), txtQtdProduto.getText(), txtValor.getText(), df.format(resultado) + ""});
    }

    public void limpaProduto() {
        txtCodProduto.setText("");
        txtProduto.setText("");
        txtQtdProduto.setText("");
        txtValor.setText("");
        txtDescontoProduto.setText("");
        lblTotalItem.setText("0,00");
        txtDescontoProduto.setEnabled(true);
    }
    
    public void botao(){
        btnAddProduto.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnAprovado.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnLimpaDesconto.setEnabled(false);
        btnLimpaDescontoOrcamento.setEnabled(false);
        btnPesquisaCliente.setEnabled(false);
        btnPesquisaProduto.setEnabled(false);
        btnRemoveProduto.setEnabled(false);
        btnSalvar.setEnabled(false);
        lblAprovado.setVisible(true);
    }
    
    public void botaoVisible(){
        btnAddProduto.setEnabled(true);
        btnAlterar.setEnabled(true);
        btnAprovado.setEnabled(true);
        btnExcluir.setEnabled(true);
        btnLimpaDesconto.setEnabled(true);
        btnLimpaDescontoOrcamento.setEnabled(true);
        btnPesquisaCliente.setEnabled(true);
        btnPesquisaProduto.setEnabled(true);
        btnRemoveProduto.setEnabled(true);
        btnSalvar.setEnabled(true);
        lblAprovado.setVisible(false);
    }

    public void limparTela() {
        DefaultTableModel model = (DefaultTableModel) tblProduto.getModel();
        txtOrcamento.setText("");
        txtCodPessoa.setText("");
        txtNome.setText("");
        txtCodProduto.setText("");
        txtProduto.setText("");
        txtQtdProduto.setText("");
        txtValor.setText("");
        txtDescontoProduto.setText("");
        lblTotalItem.setText("0,00");
        lblTotalOrcamento.setText("0,00");
        txtDescontoProduto.setEnabled(true);
        txtDescontoOrcamento.setEnabled(true);
        txtDescontoOrcamento.setEnabled(true);
        txtDescontoOrcamento.setText("");
        lblAprovado.setVisible(false);
        botaoVisible();
        model.setNumRows(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaOrcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaOrcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaOrcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaOrcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaOrcamento dialog = new TelaOrcamento(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduto;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnAprovado;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpaDesconto;
    private javax.swing.JButton btnLimpaDescontoOrcamento;
    private javax.swing.JButton btnLimpaProduto;
    private javax.swing.JButton btnLimparTela;
    private javax.swing.JButton btnPesquisaCliente;
    private javax.swing.JButton btnPesquisaProduto;
    private javax.swing.JButton btnRemoveProduto;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAprovado;
    private javax.swing.JLabel lblDescontoItem;
    private javax.swing.JLabel lblDescontoOrcamento;
    private javax.swing.JLabel lblTotalItem;
    private javax.swing.JLabel lblTotalOrcamento;
    private javax.swing.JTable tblProduto;
    private javax.swing.JTextField txtCodPessoa;
    private javax.swing.JTextField txtCodProduto;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JTextField txtDescontoOrcamento;
    private javax.swing.JTextField txtDescontoProduto;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtOrcamento;
    private javax.swing.JButton txtPesquisaOrcamento;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQtdProduto;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
